### ISSUE TITLE
para.in variables 

### ISSUE THREAD

**Issue by MarwanSherri** [zhandawei/Call_ANSYS_in_MATLAB#1]
Hello, 
Thanks for the code, 
I'm using large numbers for the design_point like 2.1E11 for some optimization case. 
the code cannot read such number
current format for input is  (10F9.0) to read the variables but cannot read. 

can you help of that ?

**Comment by zhandawei** [comment]
You can get a smaller number by dividing the large number 2.1E11 / 1E9 = 2.1E3, then read 2.1E3 into ANSYS ADPL. After that, you can multiply the 2.1E3 by 1E9 in your APDL code.
